version: '2'

networks:
  thk_blocks:

services:
  kafka1.thinking.com:
    image: ubuntu
    container_name: kafka1.thinking.com
    command: sh /kafka-cmd/kafka1.sh
    tty: true
    networks:
      - thk_blocks
    ports:
      - "9092:9092"
    volumes:
      - /mnt/hgfs/java-env/jdk1.8.0_211:/java
      - ../kafka-cmd:/kafka-cmd
      - /mnt/hgfs/zk-kafka-env/kafka_2.13-2.5.0:/kafka
      - ../kafka-logs/log-1:/tmp/kafka-logs
      - ../kafka-logs/sys-log-1:/kafka/logs
    environment:
      - JAVA_HOME=/java

  kafka2.thinking.com:
    image: ubuntu
    container_name: kafka2.thinking.com
    command: sh /kafka-cmd/kafka2.sh
    tty: true
    networks:
      - thk_blocks
    ports:
      - "9093:9092"
    volumes:
      - /mnt/hgfs/java-env/jdk1.8.0_211:/java
      - ../kafka-cmd:/kafka-cmd
      - /mnt/hgfs/zk-kafka-env/kafka_2.13-2.5.0:/kafka
      - ../kafka-logs/log-2:/tmp/kafka-logs
      - ../kafka-logs/sys-log-2:/kafka/logs
    environment:
      - JAVA_HOME=/java

  kafka3.thinking.com:
    image: ubuntu
    container_name: kafka3.thinking.com
    command: sh /kafka-cmd/kafka3.sh
    tty: true
    networks:
      - thk_blocks
    ports:
      - "9094:9092"
    volumes:
      - /mnt/hgfs/java-env/jdk1.8.0_211:/java
      - ../kafka-cmd:/kafka-cmd
      - /mnt/hgfs/zk-kafka-env/kafka_2.13-2.5.0:/kafka
      - ../kafka-logs/log-3:/tmp/kafka-logs
      - ../kafka-logs/sys-log-3:/kafka/logs
    environment:
      - JAVA_HOME=/java
      
  kafka4.thinking.com:
    image: ubuntu
    container_name: kafka4.thinking.com
    command: sh /kafka-cmd/kafka4.sh
    tty: true
    networks:
      - thk_blocks
    ports:
      - "9095:9092"
    volumes:
      - /mnt/hgfs/java-env/jdk1.8.0_211:/java
      - ../kafka-cmd:/kafka-cmd
      - /mnt/hgfs/zk-kafka-env/kafka_2.13-2.5.0:/kafka
      - ../kafka-logs/log-4:/tmp/kafka-logs
      - ../kafka-logs/sys-log-4:/kafka/logs
    environment:
      - JAVA_HOME=/java
