version: '2'

networks:
  byfn:

services:
  env:
    container_name: env
    image: ubuntu
    tty: true
    command: /bin/bash
    volumes:
    - /home/yong/go-path:/home/yong/go-path
    - /home/yong/go:/home/yong/go
    - /home/yong/Go-Stu/fabric-sdk-test:/home/yong/Go-Stu/fabric-sdk-test
    - /home/yong/fabric-samples/first-network:/home/yong/fabric-samples/first-network
    environment:
    - GOPATH=/home/yong/go-path
    - GOROOT=/home/yong/go
    - PATH=$PATH:/home/yong/go:/home/yong/go-path
    networks:
    - byfn

