apply: "com"

com:
  model: "info"
  web_site: "https://www.amazon.com"
  max_deep: 2
  delay_spider: 2
  key_words: "Fruit knife"
  prices_levels: "Under $25;$25 to $50"
  cookies:
    session_id:
      name: "session-id"
      value: "147-6489143-1689104"
      domain: ".amazon.com"
      path:  "/"
    ubid_main:
      name: "ubid-main"
      value: "132-6250557-3411723"
      domain: ".amazon.com"
      path:  "/"
  page_handler_que: "div[class='a-text-center']"
  product_items_handler_que: "div[class='s-main-slot s-result-list s-search-results sg-row']"
  pages_key: "ref"
  page_current_que: "li[class=a-selected] a[href]"
  page_next_que: "li[class=a-normal] a[href]"
  page_attr: "href"
  page_url_tag: "sr_pg_"
  page_start_tag: "nb_sb_noss"
  region_que: "div#nav-global-location-slot span[class='nav-line-2 nav-progressive-content']"
  robort_que: "div[class='a-container a-padding-double-large'] p[class='a-last']"
  items:
    product_item_que: "div[data-asin]"
    item:
      item_index_attr: "data-index"
      item_asin_attr: "data-asin"
      item_uuid_attr: "data-uuid"
      item_desc_que: "img[class='s-image']"
      item_desc_attr: "alt"
      item_range_que: "a[class='a-link-normal'] span[class='a-size-base']"
      item_price_que: "span[class='a-price'][data-a-color='base'] span[class='a-offscreen']"
      item_starts_que: "div[class='a-section a-spacing-none a-spacing-top-micro'] div[class='a-row a-size-small'] span"
      item_detail_url_que: "a[class='a-link-normal s-no-outline']"
  price_level:
    price_str_que:  "span[class='a-size-base a-color-base']"
    price_list_que: "div#priceRefinements a[data-routing][class='a-link-normal s-navigation-item']"


database:
  conn: "root:123456@(localhost:3306)/thinking_spider?charset=utf8&parseTime=True&loc=Local"
  type: "mysql"
