apply: "patents"

com:
  model: "info"
  web_site: "https://www.amazon.com"
  new_release: "https://www.amazon.com/gp/new-releases/kitchen/"
  max_deep: 10
  delay_spider: 2
  key_words: "Fruit knife"
  prices_levels: "Under $25;$25 to $50"
  cookies:
    session_id:
      name: "session-id"
      value: "135-5661648-0524928"
      domain: ".amazon.com"
      path:  "/"
    ubid_main:
      name: "ubid-main"
      value: "130-6620617-9250642"
      domain: ".amazon.com"
      path:  "/"
  page_handler_que: "div[class='a-text-center']"
  product_items_handler_que: "div[class='s-main-slot s-result-list s-search-results sg-row']"
  pages_key: "ref"
  page_current_que: "li[class=a-selected] a[href]"
  page_next_que: "li[class=a-normal] a[href]"
  page_attr: "href"
  page_url_tag: "sr_pg_"
  page_start_tag: "nb_sb_noss"
  region_que: "div#nav-global-location-slot span[class='nav-line-2 nav-progressive-content']"
  robort_que: "div[class='a-container a-padding-double-large'] p[class='a-last']"
  items:
    product_item_que: "div[data-asin]"
    item:
      item_index_attr: "data-index"
      item_asin_attr: "data-asin"
      item_uuid_attr: "data-uuid"
      item_desc_que: "img[class='s-image']"
      item_desc_attr: "alt"
      item_range_que: "a[class='a-link-normal'] span[class='a-size-base']"
      item_price_que: "span[class='a-price'][data-a-color='base'] span[class='a-offscreen']"
      item_starts_que: "div[class='a-section a-spacing-none a-spacing-top-micro'] div[class='a-row a-size-small'] span"
      item_detail_url_que: "a[class='a-link-normal s-no-outline']"
      item_img_url_que: "img[class='s-image']"
  price_level:
    price_str_que:  "span[class='a-size-base a-color-base']"
    price_list_que: "div#priceRefinements a[data-routing][class='a-link-normal s-navigation-item']"
  details:
    descs_que: "ul[class='a-unordered-list a-vertical a-spacing-mini'] li[id!='replacementPartsFitmentBullet'] span[class='a-list-item']"
    asin_que: "input[type='hidden'][id='ftSelectAsin']"
    sold_by_que: "div[class='a-fixed-left-grid a-spacing-small']"
    sold_id_que: "input[type='hidden'][id='ftSelectMerchant']"
    prod_desc_que: "div#productDescription[class='a-section a-spacing-small'] p"

patents:
  model: "info"
  web_site: "http://patft.uspto.gov"
  #web_site: "http://appft.uspto.gov"
  max_deep: 2
  delay_spider: 2
  #key_words: "http://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&p=1&u=%2Fnetahtml%2FPTO%2Fsearch-bool.html&r=0&f=S&l=50&TERM1=oven+glove&FIELD1=&co1=OR&TERM2=Oven+Mitt&FIELD2=&d=PTXT"
  #key_words: "http://appft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&p=1&u=%2Fnetahtml%2FPTO%2Fsearch-bool.html&r=0&f=S&l=50&TERM1=oven+glove&FIELD1=&co1=OR&TERM2=Oven+Mitt&FIELD2=&d=PG01"
  #key_words: "http://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&p=1&u=%2Fnetahtml%2FPTO%2Fsearch-bool.html&r=0&f=S&l=50&TERM1=Silicone+gloves&FIELD1=&co1=OR&TERM2=Silicone+Mitt&FIELD2=&d=PTXT"
  #key_words: "http://appft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&p=1&u=%2Fnetahtml%2FPTO%2Fsearch-bool.html&r=0&f=S&l=50&TERM1=Silicone+gloves&FIELD1=&co1=OR&TERM2=Silicone+Mitt&FIELD2=&d=PG01"
  #key_words: "http://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&p=1&u=%2Fnetahtml%2FPTO%2Fsearch-bool.html&r=0&f=S&l=50&TERM1=Slotted+spoon&FIELD1=&co1=OR&TERM2=Leaf+spoon&FIELD2=&d=PTXT"
  #key_words: "http://appft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&p=1&u=%2Fnetahtml%2FPTO%2Fsearch-bool.html&r=0&f=S&l=50&TERM1=Slotted+spoon&FIELD1=&co1=OR&TERM2=Leaf+spoon&FIELD2=&d=PG01"
  #key_words: "http://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&u=%2Fnetahtml%2FPTO%2Fsearch-adv.htm&r=0&f=S&l=50&d=PTXT&RS=%22Egg+Holder%22+AND+%22Egg+Storage%22&Refine=Refine+Search&Query=%22Egg+Holder%22+or+%22Egg+Storage%22+or+%22Egg+Container%22"
  #key_words: "http://appft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&u=%2Fnetahtml%2FPTO%2Fsearch-adv.html&r=0&f=S&l=50&d=PG01&OS=%22Egg+Holder%22+OR+%22Egg+Storage%22&RS=%22Egg+Holder%22+OR+%22Egg+Storage%22&TD=127&Srch1=%2522Egg+Holder%2522&Srch2=%2522Egg+Storage%2522&Conj1=OR&StartNum=&Refine=Refine+Search&Query=%22Egg+Holder%22+or+%22Egg+Storage%22+or+%22Egg+Container%22"
  key_words: "http://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&u=%2Fnetahtml%2FPTO%2Fsearch-adv.htm&r=0&f=S&l=50&d=PTXT&RS=%22Measuring+Cup%22+AND+kitchen&Refine=Refine+Search&Query=%22Measuring+Cup%22+AND+%28kitchen+or++home%29"

database:
  conn: "root:123456@(localhost:3306)/thinking_spider?charset=utf8&parseTime=True&loc=Local"
  type: "mysql"
