apply: "com"

com:
  model: "debug"
  task_index: 0
  web_site: "https://www.amazon.com"
  new_release: "https://www.amazon.com/gp/new-releases/kitchen/"
  max_deep: 10
  delay_spider: 2
  #key_words: "Fruit knife"
  key_words: "Kitchen & Dining"
  prices_levels: "Under $25;$25 to $50"
  cookies:
    - cookie:
        session_id:
          name: "session-id"
          value: "144-7059104-3803242"
          domain: ".amazon.com"
          path:  "/"
        ubid_main:
          name: "ubid-main"
          value: "133-7766908-2678768"
          domain: ".amazon.com"
          path:  "/"
        session_id_time:
          name: "session-id-time"
          value: "2082787201l"
          domain: ".amazon.com"
          path:  "/"
        i18n_prefs:
          name: "i18n-prefs"
          value: "USD"
          domain: ".amazon.com"
          path:  "/"
        session_token:
          name: "session-token"
          value: "NsqHDpg+qsbxDpQywkh+DHJjyAteAtcugaQQsZjHjE7a33HeMK7I1oKpMI+MN5bUYXsSkfbMkzS5D0yXJMsgfIcO0OeVlQDQxpYRiUF8zCzYhj6/qVwrJ2jdAoqNcWdJdFjbmrlXfShcGOXJMIMOIAJocdsg1azdbvVvh0Ry/uSfR0DRMiTr2u4/kQKyA9U6"
          domain: ".amazon.com"
          path:  "/"
        lc_main:
          name: "lc-main"
          value: "en_US"
          domain: ".amazon.com"
          path:  "/"
        csm_hit:
          name: "lc-main"
          value: "tb:s-G6GZPZWZAQ4CXWS47YA9|1620958707574&t:1620958708154&adb:adblk_no"
          domain: "www.amazon.com"
          path:  "/"
  page_handler_que: "div[class='a-text-center']"
  product_items_handler_que: "div[class='s-main-slot s-result-list s-search-results sg-row']"
  pages_key: "ref"
  page_current_que: "li[class=a-selected] a[href]"
  page_next_que: "li[class=a-normal] a[href]"
  page_attr: "href"
  page_url_tag: "sr_pg_"
  page_start_tag: "nb_sb_noss"
  region_que: "div#nav-global-location-slot span[class='nav-line-2 nav-progressive-content']"
  robort_que: "div[class='a-container a-padding-double-large'] p[class='a-last']"
  items:
    product_item_que: "div[data-asin]"
    item:
      item_index_attr: "data-index"
      item_asin_attr: "data-asin"
      item_uuid_attr: "data-uuid"
      item_desc_que: "img[class='s-image']"
      item_desc_attr: "alt"
      item_range_que: "a[class='a-link-normal'] span[class='a-size-base']"
      item_price_que: "span[class='a-price'][data-a-color='base'] span[class='a-offscreen']"
      item_starts_que: "div[class='a-section a-spacing-none a-spacing-top-micro'] div[class='a-row a-size-small'] span"
      item_detail_url_que: "a[class='a-link-normal s-no-outline']"
      item_img_url_que: "img[class='s-image']"
  price_level:
    price_str_que:  "span[class='a-size-base a-color-base']"
    price_list_que: "div#priceRefinements a[data-routing][class='a-link-normal s-navigation-item']"
  details:
    descs_que: "ul[class='a-unordered-list a-vertical a-spacing-mini'] li[id!='replacementPartsFitmentBullet'] span[class='a-list-item']"
    asin_que: "input[type='hidden'][id='ftSelectAsin']"
    sold_by_que: "div[class='a-fixed-left-grid a-spacing-small']"
    sold_id_que: "input[type='hidden'][id='ftSelectMerchant']"
    prod_desc_que: "div#productDescription[class='a-section a-spacing-small'] p"

patents:
  model: "info"
  web_site: "http://patft.uspto.gov"
  #web_site: "http://appft.uspto.gov"
  max_deep: 2
  delay_spider: 2
  key_words: "https://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&u=%2Fnetahtml%2FPTO%2Fsearch-adv.htm&r=0&f=S&l=50&d=PTXT&RS=%22rotating+hook%22+OR+%22360%B0Rotating+Folding+Hook%22&Refine=Refine+Search&Query=%22rotating+hook%22+OR+%22360%B0Rotating+Folding+Hook%22+OR+%22Utility+Hook%22"
database:
  conn: "root:123456@(localhost:3306)/thinking_spider?charset=utf8&parseTime=True&loc=Local"
  type: "mysql"
