apply: "com"

com:
  model: "info"
  time_out: 120
  task_index: 0
  web_site: "https://www.amazon.com"
  new_release: "https://www.amazon.com/gp/new-releases/kitchen/"
  max_deep: 1
  delay_spider: 5
  #key_words: "Fruit knife"
  key_words: "Kitchen & Dining"
  prices_levels: ""
  cookies:
    - cookie:
        session_id:
          name: "session-id"
          value: "145-9265937-5099825"
          domain: ".amazon.com"
          path:  "/"
        ubid_main:
          name: "ubid-main"
          value: "133-3165440-4460165"
          domain: ".amazon.com"
          path:  "/"
        session_id_time:
          name: "session-id-time"
          value: "2082787201l"
          domain: ".amazon.com"
          path:  "/"
        i18n_prefs:
          name: "i18n-prefs"
          value: "USD"
          domain: ".amazon.com"
          path:  "/"
        session_token:
          name: "session-token"
          value: "yBCgNmBNzgtQNlyoCaR74yfP4iT0QMNqp6kBy7WO7RhXqnw2s74I9FJhhpbesdYmQobMbBW4bSulopQjR7mqKxzPMaC/s5hEzApYS5n1VBCcWLWBkhV5dURrlUQliBtip7vEtbBOXdECdA/aYesCJ0O+4QP00seFC9Rdsx57pxM/RLaezZdyOJSpnBSwuXIB"
          domain: ".amazon.com"
          path:  "/"
        lc_main:
          name: "lc-main"
          value: "en_US"
          domain: ".amazon.com"
          path:  "/"
        csm_hit:
          name: "csm-hit"
          value: "tb:s-N5NX3S4N7AVAV9596CGQ|1632709715818&t:1632709716211&adb:adblk_no"
          domain: "www.amazon.com"
          path:  "/"
        skin:
          name: "skin"
          value: "noskin"
          domain: "www.amazon.com"
          path:  "/"
  page_handler_que: "div[class='a-text-center']"
  product_items_handler_que: "div[class='s-main-slot s-result-list s-search-results sg-row']"
  pages_key: "ref"
  page_current_que: "li[class=a-selected] a[href]"
  page_next_que: "li[class=a-normal] a[href]"
  page_attr: "href"
  page_url_tag: "sr_pg_"
  page_start_tag: "nb_sb_noss"
  region_que: "div#nav-global-location-slot span[class='nav-line-2 nav-progressive-content']"
  robort_que: "div[class='a-container a-padding-double-large'] p[class='a-last']"
  items:
    product_item_que: "div[data-asin]"
    item:
      item_index_attr: "data-index"
      item_asin_attr: "data-asin"
      item_uuid_attr: "data-uuid"
      item_desc_que: "img[class='s-image']"
      item_desc_attr: "alt"
      # item_range_que: "a[class='a-link-normal'] span[class='a-size-base']"
      # item_range_que: "a[class='a-link-normal s-underline-text s-underline-link-text'] span[class='a-size-base a-color-base s-underline-text']"
      # item_range_que: "a[class*='a-link-normal'] span[class*='a-size-base']"
      item_range_que: "div[class='a-row a-size-small'] span[class*='a-size-base']"
      item_price_que: "span[class='a-price'][data-a-color='base'] span[class='a-offscreen']"
      item_starts_que: "div[class='a-section a-spacing-none a-spacing-top-micro'] div[class='a-row a-size-small'] span"
      item_detail_url_que: "a[class='a-link-normal s-no-outline']"
      item_img_url_que: "img[class='s-image']"
  price_level:
    price_str_que:  "span[class='a-size-base a-color-base']"
    price_list_que: "div#priceRefinements a[data-routing][class='a-link-normal s-navigation-item']"
  details:
    descs_que: "ul[class='a-unordered-list a-vertical a-spacing-mini'] li[id!='replacementPartsFitmentBullet'] span[class='a-list-item']"
    asin_que: "input[type='hidden'][id='ftSelectAsin']"
    sold_by_que: "div[class='a-fixed-left-grid a-spacing-small']"
    sold_id_que: "input[type='hidden'][id='ftSelectMerchant']"
    prod_desc_que: "div#productDescription[class='a-section a-spacing-small'] p"

patents:
  model: "info"
  time_out: 120
  web_site: "http://patft.uspto.gov"
  #web_site: "http://appft.uspto.gov"
  max_deep: 2
  delay_spider: 2
  key_words: "https://patft.uspto.gov/netacgi/nph-Parser?Sect1=PTO2&Sect2=HITOFF&p=1&u=%2Fnetahtml%2FPTO%2Fsearch-adv.htm&r=0&f=S&l=50&d=PTXT&Query=%22Cabinet+Turntable%22+OR+%22Turntable+Storage+Container%22+OR+%22Lazy+Susan+Cabinet+Organizer%22+OR+%22lazy+susan+spice+rack+with+Dividers%22+OR+%22Lazy+Susan+Turntable+with+Dividers%22+OR+%22360+Rotating+storage+Container%22+OR+%22Divided+Lazy+Susan+Turntable%22+OR+%22Round+Rotating+Organization%22+"
database:
  conn: "root:123456@(localhost:3306)/thinking_spider?parseTime=True&loc=Local"
  type: "mysql"