zero_incre_tab_mon:
  - db1_id.sch1.*
  - db2_id.sch2.test1
  - db2_id.sch2.test2
db_conn:
  - id: db1_id
    ip_port: 0.0.0.0:5432
    user_name: yuyong
    pwd: "123456"
    db_name: db1
  - id: db2_id
    ip_port: 0.0.0.0:5433
    user_name: yuyong
    pwd: "123456"
    db_name: db2