/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_thinking_utils_Native */

#ifndef _Included_com_thinking_utils_Native
#define _Included_com_thinking_utils_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_thinking_utils_Native
 * Method:    SayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_thinking_utils_Native_SayHello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
