APP       := TestHelloApp1
TARGET    := TestHelloSer
MFLAGS    :=
DFLAGS    :=
CONFIG    := client
STRIP_FLAG:= N
J2GO_FLAG:= 

libpath=${subst :, ,$(GOPATH)}
$(foreach path,$(libpath),$(eval -include /home/yong/codes/TarsGo/tars/makefile.tars.gomod))
